### ISSUE TITLE
During docker-compose build, sbt fails to install with error 403 forbidden

### ISSUE THREAD

**Issue by nickjj** [oleksandra-holovina/docker-play-example#1]
This is due to https://github.com/sbt/sbt/issues/6582.

It looks like Bintray (the service sbt is using to host their apt repo) is potentially going away. I'm not involved with the sbt team or know the story behind Bintray but it does mean you won't be able to build this project until that issue is addressed.

If it ends up being an issue for a while we could try downloading and installing sbt manually instead of using apt.

**Comment by oleksandra-holovina** [comment]
Bintray to JFrog Artifactory migration was completed. Made the corresponding updates:
https://github.com/oleksandra-holovina/docker-play-example/pull/2

Closing the issue.
